;/*FB_PKG_DELIM*/

__d("CometGamingGamesRootSectionsQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="24700333612944880"}),null);
__d("CometGamingGamesRootSectionsQuery$Parameters",["CometGamingGamesRootSectionsQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometGamingGamesRootSectionsQuery_facebookRelayOperation"),metadata:{},name:"CometGamingGamesRootSectionsQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingLeftRailContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6883631858324529"}),null);
__d("CometGamingLeftRailContainerQuery$Parameters",["CometGamingLeftRailContainerQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometGamingLeftRailContainerQuery_facebookRelayOperation"),metadata:{},name:"CometGamingLeftRailContainerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometMarketplaceHashtagFollowButtonContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5177088882328860"}),null);
__d("CometMarketplaceHashtagFollowButtonContainerQuery$Parameters",["CometMarketplaceHashtagFollowButtonContainerQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometMarketplaceHashtagFollowButtonContainerQuery_facebookRelayOperation"),metadata:{},name:"CometMarketplaceHashtagFollowButtonContainerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("MarketplaceBannerContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7488199171211406"}),null);
__d("MarketplaceBannerContainerQuery$Parameters",["MarketplaceBannerContainerQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("MarketplaceBannerContainerQuery_facebookRelayOperation"),metadata:{},name:"MarketplaceBannerContainerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("MarketplaceCometBrowseFeedLightContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8006252572724392"}),null);
__d("MarketplaceCometBrowseFeedLightContainerQuery$Parameters",["MarketplaceCometBrowseFeedLightContainerQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("MarketplaceCometBrowseFeedLightContainerQuery_facebookRelayOperation"),metadata:{},name:"MarketplaceCometBrowseFeedLightContainerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometMarketplaceNotificationsListContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7165336436835489"}),null);
__d("CometMarketplaceNotificationsListContainerQuery$Parameters",["CometMarketplaceNotificationsListContainerQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometMarketplaceNotificationsListContainerQuery_facebookRelayOperation"),metadata:{},name:"CometMarketplaceNotificationsListContainerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometMarketplaceHashtagFeedPageHeaderQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7113522348719136"}),null);
__d("CometMarketplaceHashtagFeedPageHeaderQuery$Parameters",["CometMarketplaceHashtagFeedPageHeaderQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometMarketplaceHashtagFeedPageHeaderQuery_facebookRelayOperation"),metadata:{},name:"CometMarketplaceHashtagFeedPageHeaderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometMarketplaceLeftRailNavigationContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7005468709486162"}),null);
__d("CometMarketplaceLeftRailNavigationContainerQuery$Parameters",["CometMarketplaceLeftRailNavigationContainerQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometMarketplaceLeftRailNavigationContainerQuery_facebookRelayOperation"),metadata:{},name:"CometMarketplaceLeftRailNavigationContainerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometMarketplaceRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5760466230636291"}),null);
__d("CometMarketplaceRootQuery$Parameters",["CometMarketplaceRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometMarketplaceRootQuery_facebookRelayOperation"),metadata:{},name:"CometMarketplaceRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("buildCometGamingRoute.entrypoint",["CometGamingLeftRailContainerQuery$Parameters","JSResourceForInteraction","createContentAreaCompoundEntryPointBuilder"],(function(a,b,c,d,e,f,g){"use strict";function a(a){return c("createContentAreaCompoundEntryPointBuilder")(c("JSResourceForInteraction")("CometGamingRoot.react").__setRef("buildCometGamingRoute.entrypoint"),function(c){return{leftRailQueryReference:{parameters:b("CometGamingLeftRailContainerQuery$Parameters"),variables:{routeType:a}}}})}g["default"]=a}),98);
__d("CometGamingGamesRoot.entrypoint",["CometGamingGamesRootSectionsQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometGamingRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometGamingRoute.entrypoint")("INSTANT_GAMES")(c("JSResourceForInteraction")("CometGamingGamesRoot.react").__setRef("CometGamingGamesRoot.entrypoint"),function(a){var c,e;c=(c=a.routeParams.category)!=null?c:400;e=(e=a.routeParams.sort_type)!=null?e:"recommended";return{extraProps:{category:c,sortType:e,storeVisitSource:a.routeParams.store_visit_source},queries:{gamesSectionsQuery:{parameters:b("CometGamingGamesRootSectionsQuery$Parameters"),variables:{launched_game_id:a.routeParams.launched_game_id,scale:d("WebPixelRatio").get()}}}}});g["default"]=a}),98);
__d("buildMarketplaceRoute.entrypoint",["CometMarketplaceHashtagFeedPageHeaderQuery$Parameters","CometMarketplaceHashtagFollowButtonContainerQuery$Parameters","CometMarketplaceLeftRailNavigationContainerQuery$Parameters","CometMarketplaceRootQuery$Parameters","JSResourceForInteraction","createContentAreaCompoundEntryPointBuilder"],(function(a,b,c,d,e,f,g){"use strict";a=c("createContentAreaCompoundEntryPointBuilder")(c("JSResourceForInteraction")("CometMarketplaceRoot.react").__setRef("buildMarketplaceRoute.entrypoint"),function(a){var c=a.routeProps.location,d=c.latitude;c=c.longitude;a=a.routeParams.hashtag_id;d={leftRailQueryReference:{environmentProviderOptions:{ssrBoundary:"left_rail"},parameters:b("CometMarketplaceLeftRailNavigationContainerQuery$Parameters"),variables:{buyLocation:{latitude:d,longitude:c},category_ranking_enabled:!1,hide_l2_cats:!0}},rootQueryReference:{environmentProviderOptions:{ssrBoundary:"left_rail"},parameters:b("CometMarketplaceRootQuery$Parameters"),variables:{}}};Boolean(a)&&(d=babelHelpers["extends"]({},d,{hashtagFollowButtonQueryReference:{environmentProviderOptions:{ssrBoundary:"left_rail"},parameters:b("CometMarketplaceHashtagFollowButtonContainerQuery$Parameters"),variables:{hashtagID:a}},hashtagPageHeaderQueryReference:{environmentProviderOptions:{ssrBoundary:"left_rail"},parameters:b("CometMarketplaceHashtagFeedPageHeaderQuery$Parameters"),variables:{hashtagID:a}}}));return d});g["default"]=a}),98);
__d("MarketplaceHomeRootSharedPreloaders.entrypoint",["CometMarketplaceNotificationsListContainerQuery$Parameters","MarketplaceBannerContainerQuery$Parameters","MarketplaceCometBrowseFeedLightContainerQuery$Parameters","WebPixelRatio","gkx"],(function(a,b,c,d,e,f,g){"use strict";var h=1e3;function i(a){a=a.routeProps.location;return{feedQueryReferenceLight:{environmentProviderOptions:{ssrBoundary:"feed"},parameters:b("MarketplaceCometBrowseFeedLightContainerQuery$Parameters"),variables:{buyLocation:{latitude:a.latitude,longitude:a.longitude},count:1,cursor:null,imageWidth:256,mediaType:"image/jpeg",radius:a.radius*h,scale:d("WebPixelRatio").get(),sizing:"cover-fill-cropped",useSDFPath:!0}}}}function j(){return{notificationsQueryReference:{environmentProviderOptions:{ssrBoundary:"feed"},parameters:b("CometMarketplaceNotificationsListContainerQuery$Parameters"),variables:{isCOBMOB:c("gkx")("22968"),scale:d("WebPixelRatio").get()}}}}function a(a){a=i(a);c("gkx")("23554")&&(a=babelHelpers["extends"]({},a,j()));a=babelHelpers["extends"]({},a,{bannerV2QueryReference:{environmentProviderOptions:{ssrBoundary:"feed"},parameters:b("MarketplaceBannerContainerQuery$Parameters"),variables:{params:{render_location:"HOME_FEED"},scale:d("WebPixelRatio").get()}}});return a}g["default"]=a}),98);
__d("CometMarketplaceHomeRoot.entrypoint",["JSResourceForInteraction","MarketplaceHomeRootSharedPreloaders.entrypoint","buildMarketplaceRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildMarketplaceRoute.entrypoint")(c("JSResourceForInteraction")("CometMarketplaceHomeRoot.react").__setRef("CometMarketplaceHomeRoot.entrypoint"),function(a){a=c("MarketplaceHomeRootSharedPreloaders.entrypoint")(a);return{queries:a}});g["default"]=a}),98);