;/*FB_PKG_DELIM*/

__d("FriendingCometRootContentQuery$Parameters",["FriendingCometRootContentQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("FriendingCometRootContentQuery_facebookRelayOperation"),metadata:{},name:"FriendingCometRootContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometCrossGroupFeedContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7169965659760112"}),null);
__d("GroupsCometCrossGroupFeedContainerQuery$Parameters",["CometUFIReactionsEnableShortName.relayprovider","GroupsCometCrossGroupFeedContainerQuery_facebookRelayOperation","IsMergQAPolls.relayprovider","IsWorkUser.relayprovider","StoriesArmadilloReplyEnabled.relayprovider","StoriesRing.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometCrossGroupFeedContainerQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometCrossGroupFeedContainerQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__IsWorkUserrelayprovider:b("IsWorkUser.relayprovider"),__relay_internal__pv__IsMergQAPollsrelayprovider:b("IsMergQAPolls.relayprovider"),__relay_internal__pv__CometUFIReactionsEnableShortNamerelayprovider:b("CometUFIReactionsEnableShortName.relayprovider"),__relay_internal__pv__StoriesArmadilloReplyEnabledrelayprovider:b("StoriesArmadilloReplyEnabled.relayprovider"),__relay_internal__pv__StoriesRingrelayprovider:b("StoriesRing.relayprovider")}}};e.exports=a}),null);
__d("GroupsCometLeftRailContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4799083453548593"}),null);
__d("GroupsCometLeftRailContainerQuery$Parameters",["GroupsCometLeftRailContainerQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometLeftRailContainerQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometLeftRailContainerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomePlaylistRootQuery$Parameters",["StoriesRing.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"7081952118578911",metadata:{},name:"CometVideoHomePlaylistRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__StoriesRingrelayprovider:b("StoriesRing.relayprovider")}}};e.exports=a}),null);
__d("CometVideoHomeRootProviderQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8099333720109156"}),null);
__d("CometVideoHomeRootProviderQuery$Parameters",["CometVideoHomeRootProviderQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometVideoHomeRootProviderQuery_facebookRelayOperation"),metadata:{},name:"CometVideoHomeRootProviderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeHashtagRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6642424265842121"}),null);
__d("CometVideoHomeHashtagRootQuery$Parameters",["CometVideoHomeHashtagRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometVideoHomeHashtagRootQuery_facebookRelayOperation"),metadata:{},name:"CometVideoHomeHashtagRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeLOEExploreLeftRailSectionQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5964852866867127"}),null);
__d("CometVideoHomeLOEExploreLeftRailSectionQuery$Parameters",["CometVideoHomeLOEExploreLeftRailSectionQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometVideoHomeLOEExploreLeftRailSectionQuery_facebookRelayOperation"),metadata:{},name:"CometVideoHomeLOEExploreLeftRailSectionQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("FriendingCometRoot.entrypoint",["FriendingCometRootContentQuery$Parameters","JSResourceForInteraction","NestedRelayEntryPointBuilderUtils","ProfileCometTimelineListViewRouteRoot.entrypoint","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var e={scale:d("WebPixelRatio").get()},f=a.routeProps,g=f.profileID;f=f.viewerID;g=g!=null&&f!=null?d("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:c("ProfileCometTimelineListViewRouteRoot.entrypoint"),entryPointParams:{routeProps:{userID:a.routeProps.profileID,viewerID:a.routeProps.viewerID}}}):void 0;return{entryPoints:{profileEntryPoint:g},queries:{friendingCometRootContentQueryReference:{parameters:b("FriendingCometRootContentQuery$Parameters"),variables:e}}}},root:c("JSResourceForInteraction")("FriendingCometRoot.react").__setRef("FriendingCometRoot.entrypoint")};g["default"]=a}),98);
__d("buildCometGroupsTabRoute.entrypoint",["GroupsCometLeftRailContainerQuery$Parameters","JSResourceForInteraction","WebPixelRatio","createContentAreaCompoundEntryPointBuilder"],(function(a,b,c,d,e,f,g){"use strict";a={adminGroupsCount:3,memberGroupsCount:10,scale:d("WebPixelRatio").get()};var h={leftRailQueryReference:{parameters:c("GroupsCometLeftRailContainerQuery$Parameters"),variables:a}};b=c("createContentAreaCompoundEntryPointBuilder")(c("JSResourceForInteraction")("GroupsCometTabRoot.react").__setRef("buildCometGroupsTabRoute.entrypoint"),function(a){return h});g.buildCometGroupsTabRouteEntrypoint=b;g.cometGroupsTabRouteEntrypointQueries=h}),98);
__d("GroupsCometCrossGroupFeedRoot.entrypoint",["GroupsCometCrossGroupFeedContainerQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometGroupsTabRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=d("buildCometGroupsTabRoute.entrypoint").buildCometGroupsTabRouteEntrypoint(c("JSResourceForInteraction")("GroupsCometCrossGroupFeedRoot.react").__setRef("GroupsCometCrossGroupFeedRoot.entrypoint"),function(a){a=a.isUserLoggedOut;var c=d("WebPixelRatio").get();a={crossGroupFeedQueryRef:{parameters:b("GroupsCometCrossGroupFeedContainerQuery$Parameters"),variables:{feedbackSource:69,feedLocation:"GROUP",focusCommentID:null,isUserLoggedOut:a,privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"groups_tab",scale:c}}};return{queries:a}});g["default"]=a}),98);
__d("buildCometVideoHomeRouteForResource.entrypoint",["CometVideoHomeLOEExploreLeftRailSectionQuery$Parameters","CometVideoHomeRootProviderQuery$Parameters","createContentAreaCompoundEntryPointBuilder"],(function(a,b,c,d,e,f,g){"use strict";function a(a){return c("createContentAreaCompoundEntryPointBuilder")(a,function(a){return{exploreQueryReference:{parameters:b("CometVideoHomeLOEExploreLeftRailSectionQuery$Parameters"),variables:{}},rootProviderQueryReference:{parameters:b("CometVideoHomeRootProviderQuery$Parameters"),variables:{}}}})}g["default"]=a}),98);
__d("buildCometVideoHomeRoute.entrypoint",["JSResourceForInteraction","buildCometVideoHomeRouteForResource.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometVideoHomeRouteForResource.entrypoint")(c("JSResourceForInteraction")("CometVideoHomeRoot.react").__setRef("buildCometVideoHomeRoute.entrypoint"));g["default"]=a}),98);
__d("CometVideoHomePlaylistRoot.entrypoint",["CometVideoHomePlaylistRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometVideoHomeRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometVideoHomeRoute.entrypoint")(c("JSResourceForInteraction")("CometVideoHomePlaylistRoot.react").__setRef("CometVideoHomePlaylistRoot.entrypoint"),function(a){a={id:a.routeProps.id};return{queries:{playlistRootQueryReference:{parameters:b("CometVideoHomePlaylistRootQuery$Parameters"),variables:{scale:d("WebPixelRatio").get(),trigger_data:a}}}}});g["default"]=a}),98);
__d("CometVideoHomeHashtagRoot.entrypoint",["CometVideoHomeHashtagRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometVideoHomeRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometVideoHomeRoute.entrypoint")(c("JSResourceForInteraction")("CometVideoHomeHashtagRoot.react").__setRef("CometVideoHomeHashtagRoot.entrypoint"),function(a){a={hashtag:a.routeProps.id};return{queries:{queryReference:{parameters:b("CometVideoHomeHashtagRootQuery$Parameters"),variables:{scale:d("WebPixelRatio").get(),triggerData:a}}}}});g["default"]=a}),98);
__d("CometVideoHomeFeedRoot.entrypoint",["CometVideoHomeFeedEntryPointVariables","CometVideoHomeFeedRootQuery$Parameters","CometVideoHomeSurfaceHighlightsWrapperQuery$Parameters","JSResourceForInteraction","buildCometVideoHomeRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometVideoHomeRoute.entrypoint")(c("JSResourceForInteraction")("CometVideoHomeFeedRoot.react").__setRef("CometVideoHomeFeedRoot.entrypoint"),function(a){return{queries:{feedRootQueryReference:{options:{fetchPolicy:"network-only"},parameters:b("CometVideoHomeFeedRootQuery$Parameters"),variables:c("CometVideoHomeFeedEntryPointVariables")},surfaceHighlightsQueryReference:{parameters:b("CometVideoHomeSurfaceHighlightsWrapperQuery$Parameters"),variables:{}}}}});g["default"]=a}),98);